services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: grpc_test_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports :
      - 54321:5432

volumes:
  pgdata: